import type { Metadata } from "next";
import { Red_Rose } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const redrose = Red_Rose({
  variable: "--font-red-rose",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Synctom Softwares",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${redrose.className} max-w-340  mx-auto antialiased`}>
        <Header />
        <main className="pt-20">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
